server:
  port: 9111
  ssl:
    key-store: classpath:keystore.jks
    key-store-password: password
    key-alias: myapp
    key-password: password
  servlet:
    context-path: /pizza/api

spring:
  web:
    resource:
      static-location: classpath:/static/

  datasource:
    url: jdbc:mysql://pizza-db.cx0684ea6lf5.us-west-1.rds.amazonaws.com:3306/PizzaStore
    username: admin
    password: pizzaadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-circular-references: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
    repositories:
      enabled: true